### PR TITLE
Fix Copyright in README

### PR DESCRIPTION
**Pull request by kennyadsl**
🤔

### CODE REVIEW

**Review by aldesantis — APPROVED** [review]
No idea how that happened 🤦

**Review by elia — CHANGES_REQUESTED** [review]
If we want to change the copyright we should at least _also_ preserve the original, being NewBSD I think we're allowed to do that, but not to remove the original license (as proposed by @ccarruitero in #59).

For the record, the history of this change is the following:
- an [update done with solidus_dev_support](https://github.com/solidusio/solidus_stripe/commit/c41b75b0a7f74f88f01fe827fd355deb59c7f292#diff-9879d6db96fd29134fc802214163b95a) brought in an additional `LICENSE` file in addition to the already existing `LICENSE.md`
- the older file was subsequently [removed by yours truly](https://github.com/solidusio/solidus_stripe/commit/3a79c59ad5b4300d4c0e3a939d6c831536bcbf1b) restoring the original copyright

**Comment by spaghetticode** [comment]
Fixes #59

**Comment by kennyadsl** [comment]
I opened the PR, so I can't approve, but I approve!

**Comment by spaghetticode** [comment]
Luckily for us (I can't approve it either, as I edited the PR) @aldesantis had already approved it 🎉 🤪

**Comment by spaghetticode** [comment]
CI failure is not related to changes, so merging it anyway.

**Pull request merged**
